<a href="https://colab.research.google.com/github/koushik-sivan/Lead_conversion_for_X_company/blob/main/Koushik_S_Lead_Conversion_For_X_Company.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Connecting to Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


Importing Libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Reading CSVs

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/dsml-case-study/train.csv')
test_data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dsml-case-study/test.csv")
submission_data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dsml-case-study/sample_submission.csv")

Checking Data

In [ ]:
df.head()
test_data.head()

Id                           Prospect ID  Lead Number  \
0  8305  54eb2a3d-cb6b-4616-b6e9-c80d8a9dbca4       586427   
1  1591  0ca87aef-fa6a-4b3c-acf7-36c1520e8a53       643772   
2  8604  6c3e541e-0a1a-4636-b4fa-d026488a33ac       584076   
3  1333  fff49ad0-6015-448c-a7cc-f454c39ffdda       645818   
4  4260  f880fcdd-3d15-408d-a716-e71801a6c420       619066   

               Lead Origin     Lead Source Do Not Email Do Not Call  \
0                      API      Olark Chat           No          No   
1                      API          Google           No          No   
2  Landing Page Submission          Google           No          No   
3  Landing Page Submission  Direct Traffic           No          No   
4  Landing Page Submission  Direct Traffic           No          No   

   TotalVisits  Total Time Spent on Website  Page Views Per Visit  ...  \
0          0.0                            0                   0.0  ...   
1          2.0                         1069                   2.0  ...   
2         20.0                          165                   5.0  ...   
3          1.0                          471                   1.0  ...   
4          1.0                            2                   1.0  ...   

  Get updates on DM Content Lead Profile    City Asymmetrique Activity Index  \
0                        No          NaN     NaN                     01.High   
1                        No       Select  Select                   02.Medium   
2                        No       Select  Mumbai                   02.Medium   
3                        No          NaN     NaN                     01.High   
4                        No       Select  Mumbai                         NaN   

  Asymmetrique Profile Index Asymmetrique Activity Score  \
0                  02.Medium                        17.0   
1                  02.Medium                        15.0   
2                    01.High                        15.0   
3                    01.High                        16.0   
4                        NaN                         NaN   

  Asymmetrique Profile Score I agree to pay the amount through cheque  \
0                       15.0                                       No   
1                       15.0                                       No   
2                       18.0                                       No   
3                       17.0                                       No   
4                        NaN                                       No   

  A free copy of Mastering The Interview Last Notable Activity  
0                                     No          Email Opened  
1                                     No          Email Opened  
2                                    Yes              SMS Sent  
3                                     No              Modified  
4                                    Yes              Modified  

[5 rows x 37 columns]

In [ ]:
df.info()
test_data.info()

In [ ]:
df.describe()
test_data.describe()

In [ ]:
df.shape

(6468, 38)

In [ ]:
test_data.shape

(2772, 37)

Checking Null count %

In [ ]:
round(100*(df.isnull().sum()/len(df)), 2).sort_values(ascending=False)

Lead Quality                                     51.16
Asymmetrique Profile Score                       45.35
Asymmetrique Activity Score                      45.35
Asymmetrique Profile Index                       45.35
Asymmetrique Activity Index                      45.35
Tags                                             35.96
Lead Profile                                     28.87
What matters most to you in choosing a course    28.87
What is your current occupation                  28.66
Country                                          26.79
How did you hear about X Education               23.55
Specialization                                   15.37
City                                             15.15
TotalVisits                                       1.56
Page Views Per Visit                              1.56
Last Activity                                     1.14
Lead Source                                       0.40
Receive More Updates About Our Courses            0.00
I agree to

In [ ]:
round(100*(test_data.isnull().sum()/len(test_data)), 2).sort_values(ascending=False)

Lead Quality                                     52.60
Asymmetrique Activity Index                      46.36
Asymmetrique Profile Score                       46.36
Asymmetrique Activity Score                      46.36
Asymmetrique Profile Index                       46.36
Tags                                             37.05
Lead Profile                                     30.38
What matters most to you in choosing a course    30.38
What is your current occupation                  30.16
Country                                          26.26
How did you hear about X Education               24.68
Specialization                                   16.02
City                                             15.87
Page Views Per Visit                              1.30
TotalVisits                                       1.30
Last Activity                                     1.05
Lead Source                                       0.36
Receive More Updates About Our Courses            0.00
I agree to

Checking Value count of Target Variable

In [ ]:
df.Converted.value_counts(normalize=True)

Converted
0    0.614564
1    0.385436
Name: proportion, dtype: float64

In [ ]:
df["Do Not Call"].value_counts(dropna=False)

Do Not Call
No     6466
Yes       2
Name: count, dtype: int64

In [ ]:
for col in df:
    print(df[col].value_counts(ascending=False), '\n\n\n')

In [ ]:
df_dup = df.copy()
td_dup = test_data.copy()

In [ ]:
columns_to_drop = ['Id', 'Prospect ID', 'Lead Number', 'What matters most to you in choosing a course', 'Magazine',
       'Newspaper Article', 'X Education Forums', 'Newspaper',
       'Digital Advertisement', 'Through Recommendations',
       'Receive More Updates About Our Courses',
       'Update me on Supply Chain Content', 'Get updates on DM Content',
       'I agree to pay the amount through cheque']
# 'Do Not Call'

In [ ]:
df_dummy = df_dup.drop(columns=[col for col in df.columns if col in columns_to_drop])
td_dummy = td_dup.drop(columns=[col for col in test_data.columns if col in columns_to_drop])

In [ ]:
df_dummy.shape

(6468, 24)

In [ ]:
td_dummy.shape

(2772, 23)

Filling the NULL values

In [ ]:
df["Lead Quality"].value_counts(dropna=False)

Lead Quality
NaN                  3309
Might be             1123
Not Sure              761
High in Relevance     446
Worst                 420
Low in Relevance      409
Name: count, dtype: int64

In [ ]:
df_dummy["Lead Quality"].value_counts(dropna=False)
df_dummy["Lead Quality"].fillna("None",inplace=True)

In [ ]:
df_dummy["Asymmetrique Profile Score"].value_counts(dropna=False)
df_dummy["Asymmetrique Activity Score"].value_counts(dropna=False)
df_dummy["Asymmetrique Activity Index"].value_counts(dropna=False)
df_dummy["Asymmetrique Profile Index"].value_counts(dropna=False)

Asymmetrique Profile Index
NaN          2933
02.Medium    1977
01.High      1535
03.Low         23
Name: count, dtype: int64

In [ ]:
df_dummy["Asymmetrique Profile Score"].median()
df_dummy["Asymmetrique Activity Score"].median()
df_dummy["Asymmetrique Activity Index"].mode()
df_dummy["Asymmetrique Profile Index"].mode()

0    02.Medium
Name: Asymmetrique Profile Index, dtype: object

In [ ]:
df_dummy["Asymmetrique Profile Score"].fillna(df_dummy["Asymmetrique Profile Score"].median(),inplace=True)
df_dummy["Asymmetrique Activity Score"].fillna(df_dummy["Asymmetrique Activity Score"].median(),inplace=True)
df_dummy["Asymmetrique Activity Index"].fillna("02.Medium",inplace=True)
df_dummy["Asymmetrique Profile Index"].fillna("02.Medium",inplace=True)

In [ ]:
df_dummy["Tags"].value_counts(dropna=False)
df_dummy["Tags"].fillna("None",inplace=True)

In [ ]:
df_dummy["Lead Profile"].value_counts(dropna=False)
df_dummy["Lead Profile"].fillna("None",inplace=True)

In [ ]:
df_dummy["What is your current occupation"].value_counts(dropna=False)
df_dummy["What is your current occupation"].mode()
df_dummy["What is your current occupation"].fillna("Unemployed",inplace=True)

In [ ]:
df_dummy["Country"].value_counts(dropna=False)
df_dummy["Country"].fillna("None",inplace=True)

In [ ]:
df_dummy["How did you hear about X Education"].value_counts(dropna=False)
df_dummy["How did you hear about X Education"].fillna("None",inplace=True)

In [ ]:
df_dummy["Specialization"].value_counts(dropna=False)
df_dummy["Specialization"].fillna("None",inplace=True)

In [ ]:
df_dummy["City"].value_counts(dropna=False)
df_dummy["City"].fillna("None",inplace=True)

In [ ]:
df_dummy["TotalVisits"].value_counts(dropna=False)
df_dummy["TotalVisits"].fillna(df_dummy["TotalVisits"].median(),inplace=True)

In [ ]:
df_dummy["Page Views Per Visit"].value_counts(dropna=False)
df_dummy["Page Views Per Visit"].fillna(df_dummy["Page Views Per Visit"].mean(),inplace=True)

In [ ]:
df_dummy["Last Activity"].value_counts(dropna=False)
df_dummy["Last Activity"].fillna("Email Opened",inplace=True)

In [ ]:
df_dummy["Lead Source"].value_counts(dropna=False)
df_dummy["Lead Source"].fillna("Google",inplace=True)

In [ ]:
td_dummy["Lead Quality"].value_counts(dropna=False)
td_dummy["Lead Quality"].fillna("None",inplace=True)

In [ ]:
td_dummy["Asymmetrique Profile Score"].value_counts(dropna=False)
td_dummy["Asymmetrique Activity Score"].value_counts(dropna=False)
td_dummy["Asymmetrique Activity Index"].value_counts(dropna=False)
td_dummy["Asymmetrique Profile Index"].value_counts(dropna=False)

In [ ]:
td_dummy["Asymmetrique Profile Score"].median()
td_dummy["Asymmetrique Activity Score"].median()
td_dummy["Asymmetrique Activity Index"].mode()
td_dummy["Asymmetrique Profile Index"].mode()

In [ ]:
td_dummy["Asymmetrique Profile Score"].fillna(td_dummy["Asymmetrique Profile Score"].median(),inplace=True)
td_dummy["Asymmetrique Activity Score"].fillna(td_dummy["Asymmetrique Activity Score"].median(),inplace=True)
td_dummy["Asymmetrique Activity Index"].fillna("02.Medium",inplace=True)
td_dummy["Asymmetrique Profile Index"].fillna("02.Medium",inplace=True)

In [ ]:
td_dummy["Tags"].value_counts(dropna=False)
td_dummy["Tags"].fillna("None",inplace=True)

In [ ]:
td_dummy["Lead Profile"].value_counts(dropna=False)
td_dummy["Lead Profile"].fillna("None",inplace=True)

In [ ]:
td_dummy["What is your current occupation"].value_counts(dropna=False)
td_dummy["What is your current occupation"].mode()
td_dummy["What is your current occupation"].fillna("Unemployed",inplace=True)

In [ ]:
td_dummy["Country"].value_counts(dropna=False)
td_dummy["Country"].fillna("None",inplace=True)

In [ ]:
td_dummy["How did you hear about X Education"].value_counts(dropna=False)
td_dummy["How did you hear about X Education"].fillna("None",inplace=True)

In [ ]:
td_dummy["Specialization"].value_counts(dropna=False)
td_dummy["Specialization"].fillna("None",inplace=True)

In [ ]:
td_dummy["City"].value_counts(dropna=False)
td_dummy["City"].fillna("None",inplace=True)

In [ ]:
td_dummy["TotalVisits"].value_counts(dropna=False)
td_dummy["TotalVisits"].fillna(td_dummy["TotalVisits"].median(),inplace=True)

In [ ]:
td_dummy["Page Views Per Visit"].value_counts(dropna=False)
td_dummy["Page Views Per Visit"].fillna(td_dummy["Page Views Per Visit"].mean(),inplace=True)

In [ ]:
td_dummy["Last Activity"].value_counts(dropna=False)
td_dummy["Last Activity"].fillna("Email Opened",inplace=True)

In [ ]:
td_dummy["Lead Source"].value_counts(dropna=False)
td_dummy["Lead Source"].fillna("Google",inplace=True)

In [ ]:
df_dummy["Lead Source"].replace('google','Google',inplace=True)
td_dummy["Lead Source"].replace('google','Google',inplace=True)

In [ ]:
df_dummy['Do Not Email'] = df_dummy['Do Not Email'].replace({'Yes': 1, 'No': 0})
df_dummy['Search'] = df_dummy['Search'].replace({'Yes': 1, 'No': 0})
df_dummy['A free copy of Mastering The Interview'] = df_dummy['A free copy of Mastering The Interview'].replace({'Yes': 1, 'No': 0})
df_dummy['Do Not Call'] = df_dummy['Do Not Call'].replace({'Yes': 1, 'No': 0})

In [ ]:
td_dummy['Do Not Email'] = td_dummy['Do Not Email'].replace({'Yes': 1, 'No': 0})
td_dummy['Search'] = td_dummy['Search'].replace({'Yes': 1, 'No': 0})
td_dummy['A free copy of Mastering The Interview'] = td_dummy['A free copy of Mastering The Interview'].replace({'Yes': 1, 'No': 0})
td_dummy['Do Not Call'] = td_dummy['Do Not Call'].replace({'Yes': 1, 'No': 0})

Label Encoding

In [ ]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df_dummy['Asymmetrique Activity Index']= label_encoder.fit_transform(df_dummy['Asymmetrique Activity Index'])
df_dummy['Asymmetrique Activity Index'].unique()
df_dummy['Asymmetrique Profile Index']= label_encoder.fit_transform(df_dummy['Asymmetrique Profile Index'])
df_dummy['Asymmetrique Profile Index'].unique()

array([0, 1, 2])

In [ ]:
df_dummy['Asymmetrique Activity Index']

In [ ]:
label_encoder.inverse_transform([0])

array([0])

In [ ]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
td_dummy['Asymmetrique Activity Index']= label_encoder.fit_transform(td_dummy['Asymmetrique Activity Index'])
td_dummy['Asymmetrique Activity Index'].unique()
td_dummy['Asymmetrique Profile Index']= label_encoder.fit_transform(td_dummy['Asymmetrique Profile Index'])
td_dummy['Asymmetrique Profile Index'].unique()

array([1, 0, 2])

One Hot Encoding

In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

categorical_columns = df_dummy.select_dtypes(include=['object']).columns.tolist()

encoder = OneHotEncoder(sparse_output=False)

one_hot_encoded = encoder.fit_transform(df_dummy[categorical_columns])

one_hot_df = pd.DataFrame(one_hot_encoded, columns=encoder.get_feature_names_out(categorical_columns))

df_encoded = pd.concat([df_dummy, one_hot_df], axis=1)

df_encoded = df_encoded.drop(categorical_columns, axis=1)

In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

categorical_columns = td_dummy.select_dtypes(include=['object']).columns.tolist()

encoder = OneHotEncoder(sparse_output=False)

one_hot_encoded = encoder.fit_transform(td_dummy[categorical_columns])

one_hot_td = pd.DataFrame(one_hot_encoded, columns=encoder.get_feature_names_out(categorical_columns))

td_encoded = pd.concat([td_dummy, one_hot_td], axis=1)

td_encoded = td_encoded.drop(categorical_columns, axis=1)

Removing Extra columns

In [ ]:
extra_cols = df_encoded.columns.difference(td_encoded.columns)
extra_cols = extra_cols.drop("Converted")
df_encoded = df_encoded.drop(extra_cols, axis=1)

In [ ]:
extra_cols

Index([], dtype='object')

In [ ]:
extra_cols = td_encoded.columns.difference(df_encoded.columns)
td_encoded = td_encoded.drop(extra_cols, axis=1)

In [ ]:
df_encoded.shape

(6468, 157)

In [ ]:
df_encoded["Converted"]

In [ ]:
# df_none = df_encoded.columns.to_list()

In [ ]:
# df_none_columns = []
# for i in df_none:
#   if i.endswith('None'):
#     df_none_columns.append(i)

In [ ]:
# df_none_columns

['Country_None',
 'Specialization_None',
 'How did you hear about X Education_None',
 'Tags_None',
 'Lead Quality_None',
 'Lead Profile_None',
 'City_None']

In [ ]:
# td_none = td_encoded.columns.to_list()

In [ ]:
# td_none_columns = []
# for i in td_none:
#   if i.endswith('None'):
#     td_none_columns.append(i)

In [ ]:
# td_none_columns

['Country_None',
 'Specialization_None',
 'How did you hear about X Education_None',
 'Tags_None',
 'Lead Quality_None',
 'Lead Profile_None',
 'City_None']

Performing Logistic Regression

In [ ]:
help(model.fit)

Help on method fit in module sklearn.linear_model._logistic:

fit(X, y, sample_weight=None) method of sklearn.linear_model._logistic.LogisticRegression instance
    Fit the model according to the given training data.
    
    Parameters
    ----------
    X : {array-like, sparse matrix} of shape (n_samples, n_features)
        Training vector, where `n_samples` is the number of samples and
        `n_features` is the number of features.
    
    y : array-like of shape (n_samples,)
        Target vector relative to X.
    
    sample_weight : array-like of shape (n_samples,) default=None
        Array of weights that are assigned to individual samples.
        If not provided, then each sample is given unit weight.
    
        .. versionadded:: 0.17
           *sample_weight* support to LogisticRegression.
    
    Returns
    -------
    self
        Fitted estimator.
    
    Notes
    -----
    The SAGA solver supports both float64 and float32 bit arrays.



In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

In [ ]:
X_train = df_encoded.drop("Converted", axis=1)
y_train = df_encoded["Converted"]
model = LogisticRegression()
model.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
help(LogisticRegression())

Help on LogisticRegression in module sklearn.linear_model._logistic object:

class LogisticRegression(sklearn.linear_model._base.LinearClassifierMixin, sklearn.linear_model._base.SparseCoefMixin, sklearn.base.BaseEstimator)
 |  LogisticRegression(penalty='l2', *, dual=False, tol=0.0001, C=1.0, fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver='lbfgs', max_iter=100, multi_class='auto', verbose=0, warm_start=False, n_jobs=None, l1_ratio=None)
 |  
 |  Logistic Regression (aka logit, MaxEnt) classifier.
 |  
 |  In the multiclass case, the training algorithm uses the one-vs-rest (OvR)
 |  scheme if the 'multi_class' option is set to 'ovr', and uses the
 |  cross-entropy loss if the 'multi_class' option is set to 'multinomial'.
 |  (Currently the 'multinomial' option is supported only by the 'lbfgs',
 |  'sag', 'saga' and 'newton-cg' solvers.)
 |  
 |  This class implements regularized logistic regression using the
 |  'liblinear' library, 'newton-cg', '

In [ ]:
model.coef_

array([[-6.08726850e-01,  5.13497448e-03,  2.88743477e-02,
         2.03095972e-03, -1.24585941e-01,  3.15426576e-03,
        -3.31724389e-01, -4.86697743e-01,  2.18363860e-01,
        -1.49527297e-01, -2.71160765e-01, -5.19840481e-01,
        -5.69978568e-01,  1.00409621e+00, -7.27748024e-02,
         1.27275712e-03, -5.11002400e-01, -7.66052564e-02,
        -7.77635634e-02,  2.20918272e-03, -2.76368127e-01,
        -9.84553789e-02,  5.73988071e-01, -8.50006686e-02,
         3.99545683e-01, -2.66236651e-03,  1.72984118e-02,
        -3.30473550e-01, -3.39376457e-01, -4.39300930e-02,
         3.25853999e-01,  2.40936645e-03, -3.89637237e-03,
         3.51633009e-02, -7.37363372e-01, -2.49337835e-01,
         1.21218734e+00, -1.44932167e-02, -3.32391020e-02,
         1.87512484e-03, -8.69086239e-04, -1.18345520e-02,
         1.85470466e-03,  1.21773031e-03, -5.56414807e-03,
        -4.13562906e-03,  2.97932145e-03, -2.12615622e-03,
         8.31096330e-05, -5.92535804e-01, -8.39109515e-0

In [ ]:
predictions = model.predict(td_encoded)

In [ ]:
predictions

array([0, 1, 1, ..., 0, 1, 1])

In [ ]:
submission_data['Converted'] = predictions

In [ ]:
submission_data

In [ ]:
submission_data.to_csv("/content/drive/MyDrive/Colab Notebooks/dsml-case-study/submission.csv",index=False)

In [ ]:
# accuracy = accuracy_score(td_encoded["Converted"], predictions)
# recall = recall_score(td_encoded["Converted"], predictions)
# print(confusion_matrix(td_encoded["Converted"], predictions))
# print(f"Model Accuracy: {accuracy:.4f}")
# print(f"Model Recall: {recall:.4f}")